debug

diff --git a/.github/workflows/metadata curator.yaml b/.github/workflows/metadata curator.yaml
--- a/.github/workflows/metadata curator.yaml
+++ b/.github/workflows/metadata curator.yaml
@@ -186,3 +186,8 @@ jobs:
         if: ${{ failure() }}
         run: |
           docker logs --since 40m mc_formio || echo "formio container not found"
+      
+      - name: "output mc keycloak logs"
+        if: ${{ failure() }}
+        run: |
+          docker logs --since 40m mc_keycloak || echo "formio container not found"
